### ISSUE TITLE
[TWM only] Tooltip causes null pointer on Trace view

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpcviewer.e4#40]
Platform: Linux x86_64
Window manager: TWM only. Works fine on Gnome WM and macOS
Procedures (not reproducible, most of the time it works): 
- Open a database,
- Click the trace view
- Hover to no activity
- Null pointer exception is triggered

```
!SESSION 2020-11-30 21:07:02.214 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -clearPersistedState
Command-line arguments:  -os linux -ws gtk -arch x86_64 -clearPersistedState

!ENTRY org.eclipse.e4.ui.workbench 4 0 2020-11-30 21:11:36.966
!MESSAGE Internal Error
!STACK 0
java.lang.NullPointerException
	at edu.rice.cs.hpctraceviewer.ui.internal.AbstractTimeCanvas$BufferedCanvasToolTip.getText(AbstractTimeCanvas.java:272)
	at org.eclipse.jface.window.DefaultToolTip.createToolTipContentArea(DefaultToolTip.java:95)
	at org.eclipse.jface.window.ToolTip.toolTipShow(ToolTip.java:345)
	at org.eclipse.jface.window.ToolTip.lambda$2(ToolTip.java:467)
	at org.eclipse.swt.widgets.Display.timerProc(Display.java:5588)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4444)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

**Comment by laksono** [comment]
The impact has been fixed, but not the root cause. Is it good enough?
