### ISSUE TITLE
Error while opening huge text file

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpcviewer.e4#47]
Tested platform: Linux (but should fail also in other platforms).
Database: DCA++
* Open a huge database with huge XML file like DCA++ which has 286 MB.
* Open bottom-up and flat views, and also trace view.
* Open the experiment.xml file
```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2020-12-14 09:48:38.730
!MESSAGE Internal Error
!STACK 0
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:174)
	at edu.rice.cs.hpcviewer.ui.parts.editor.Editor.lambda$0(Editor.java:146)
	at edu.rice.cs.hpcviewer.ui.parts.editor.Editor$$Lambda$279/0x0000000840524440.accept(Unknown Source)
	at java.base/java.nio.file.FileChannelLinesSpliterator.forEachRemaining(FileChannelLinesSpliterator.java:114)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at edu.rice.cs.hpcviewer.ui.parts.editor.Editor.readLineByLineJava8(Editor.java:146)
	at edu.rice.cs.hpcviewer.ui.parts.editor.Editor.displayFile(Editor.java:281)
	at edu.rice.cs.hpcviewer.ui.parts.editor.Editor.setInput(Editor.java:258)
	at edu.rice.cs.hpcviewer.ui.ProfilePart.addEditor(ProfilePart.java:164)
	at edu.rice.cs.hpcviewer.ui.handlers.ViewXML.execute(ViewXML.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$$Lambda$221/0x00000008404b9040.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
```

**Comment by laksono** [comment]
Opening a big file with `newLength`=301 989 886, and `original` size=150 994 942 causes this issue. Inside Java `copyOf` procedure:
```
    public static byte[] copyOf(byte[] original, int newLength) {
        byte[] copy = new byte[newLength];
```

**Comment by laksono** [comment]
No Eclipse solution yet to open large file in SourceViewer:
https://stackoverflow.com/questions/1692329/viewing-large-xml-files-in-eclipse
https://www.eclipse.org/forums/index.php/t/160877/
