### ISSUE TITLE
Null pointer exception when manipulating views of 2 databases

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpcviewer.e4#57]
How to:

1. Open 2 databases
2. Click the menu "View - Split" to split 2 databases so the left stack is the 1st DB, while the right stack is the 2nd one.
3. Close the first database
4. The left stack will be empty, but the right stack contains the 2nd database. Move a profile part to the left stack
5. An error message will appear

![image](https://user-images.githubusercontent.com/8781032/105778478-1c232180-5f32-11eb-8da0-5772ff963459.png)

Another error:

![image](https://user-images.githubusercontent.com/8781032/105778502-247b5c80-5f32-11eb-8125-8973ebc6f0db.png)

**Comment by laksono** [comment]
Exception call stack:
```

!ENTRY org.eclipse.e4.ui.workbench 4 0 2021-01-25 19:04:10.242
!MESSAGE Internal Error
!STACK 0
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Table.drawInteriorWithFrame_inView(Table.java:1086)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6492)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:769)
	at org.eclipse.swt.widgets.Table.drawRect(Table.java:1217)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6037)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5317)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5710)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:92)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3833)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

!ENTRY org.eclipse.core.commands 4 2 2021-01-25 19:04:21.132
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.commands".
!STACK 0
java.lang.NullPointerException
	at edu.rice.cs.hpctraceviewer.ui.main.SpaceTimeDetailCanvas.refresh(SpaceTimeDetailCanvas.java:1127)
	at edu.rice.cs.hpctraceviewer.ui.main.SpaceTimeDetailCanvas.zoom(SpaceTimeDetailCanvas.java:272)
	at edu.rice.cs.hpctraceviewer.ui.main.SpaceTimeDetailCanvas$HistoryOperation.run(SpaceTimeDetailCanvas.java:1500)
	at edu.rice.cs.hpctraceviewer.ui.main.SpaceTimeDetailCanvas.historyNotification(SpaceTimeDetailCanvas.java:1309)
	at org.eclipse.core.commands.operations.DefaultOperationHistory$2.run(DefaultOperationHistory.java:876)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.notifyListeners(DefaultOperationHistory.java:865)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.notifyAboutToExecute(DefaultOperationHistory.java:887)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:493)
	at edu.rice.cs.hpctraceviewer.ui.main.SpaceTimeDetailCanvas$DetailBufferPaint.rebuffering(SpaceTimeDetailCanvas.java:1470)
	at edu.rice.cs.hpctraceviewer.ui.internal.ResizeListener.run(ResizeListener.java:32)
	at org.eclipse.swt.widgets.Display.runTimers(Display.java:4417)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3830)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
```

**Comment by laksono** [comment]
It seems the problem is due to race condition inside trace viewer. 
If we open 2 databases, and close the first one, a null pointer exception occurs since the master buffer is disposed.
```
Thread [pool-12-thread-1] (Suspended (exception NullPointerException))	
	LargeByteBuffer.getBuffer(int) line: 82	
	LargeByteBuffer.getLong(long) line: 117	
	FileDB2.getLong(long) line: 194	
	BaseData(AbstractBaseData).getLong(long) line: 52	
	TraceDataByRank.findTimeInInterval(long, long, long) line: 296	
	TraceDataByRank.readInData(int, long, long, double) line: 78	
	ProcessTimeline.readInData() line: 103	
	TimelineThread.init(ProcessTimeline) line: 98	
	TimelineThread(BaseTimelineThread).call() line: 85	
	TimelineThread(BaseTimelineThread).call() line: 1	
	FutureTask<V>.run() line: 264	
	Executors$RunnableAdapter<T>.call() line: 515	
	ExecutorCompletionService$QueueingFuture<V>(FutureTask<V>).run() line: 264	
	ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1128	
	ThreadPoolExecutor$Worker.run() line: 628	
	Thread.run() line: 834	
```
