### ISSUE TITLE
[ppc64le and Arm] deadlock when rendering the trace view

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpcviewer.e4#64]
This issue occurs on Linux ppc64le and Arm platforms. It works fine on Linux x86_64.
How to reproduce:
1. Open a huge trace database
2. Go to trace view
3. Make some changes in the range of the view (zoom-in, zoom-out, move left/right/up/down) for at least 10 times
4. Rapidly click the undo button as fast as possible, at least 2 times per second.
5. There should be a deadlock when rendering the trace view

A possible issue is because some Java threads caught the cancellation event, some not. As shown in the snapshot below:

Call stack of thread 1 to 6:

![image](https://user-images.githubusercontent.com/8781032/106323298-cf469000-623c-11eb-9459-479ad85d6852.png)

Call stack of thread 7 to 8:

![image](https://user-images.githubusercontent.com/8781032/106323319-da99bb80-623c-11eb-9910-206ffc397ef4.png)

Call stack of thread 9 to 11:

![image](https://user-images.githubusercontent.com/8781032/106323344-e7b6aa80-623c-11eb-8838-7dd73f256627.png)

**Comment by laksono** [comment]
hpcviewer built with latest Eclipse (2020.12) causes crash in JVM 11 on ARM:
```
#0  0x0000ffffae41ae90 in raise (sig=5) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000ffff6087b520 in g_log_writer_default () at /lib64/libglib-2.0.so.0
#2  0x0000ffff60879b18 in g_log_structured_array () at /lib64/libglib-2.0.so.0
#3  0x0000ffff60879de8 in g_log_structured () at /lib64/libglib-2.0.so.0
#4  0x0000ffff7c09292c in _gdk_x11_display_error_event () at /lib64/libgdk-3.so.0
#5  0x0000ffff7c0a01bc in gdk_x_error () at /lib64/libgdk-3.so.0
#6  0x0000ffff605143d0 in _XError () at /lib64/libX11.so.6
#7  0x0000ffff60511110 in handle_error () at /lib64/libX11.so.6
#8  0x0000ffff605111fc in handle_response () at /lib64/libX11.so.6
#9  0x0000ffff60511b58 in _XEventsQueued () at /lib64/libX11.so.6
#10 0x0000ffff60503a6c in XPending () at /lib64/libX11.so.6
#11 0x0000ffff7c09a398 in gdk_event_source_check () at /lib64/libgdk-3.so.0
#12 0x0000ffff60872c34 in g_main_context_check () at /lib64/libglib-2.0.so.0
#13 0x0000ffff13b280f8 in Java_org_eclipse_swt_internal_gtk_OS_g_1main_1context_1check () at /home/la5/.hpctoolkit/hpcviewer/aarch64/org.eclipse.osgi/94/0/.cp/libswt-pi3-gtk-4940r23.so
#14 0x0000ffff985c2dd0 in  ()
#15 0x0000ffff985c40c8 in  ()
```
Java version:
```
$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+9-201912311630)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+9-201912311630, mixed mode)
```

**Comment by laksono** [comment]
Deadlock in the main thread on arm 64 according to visualvm. Somehow SWT get stuck while painting a rectangle

![image](https://user-images.githubusercontent.com/8781032/118728471-d7c9d300-b7f9-11eb-8701-29e739f94439.png)

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpcviewer/-/issues/64)
