### ISSUE TITLE
Inefficient memory utilization

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpcviewer.e4#68]
Opening a huge database like DCA++ invokes GC which slow down the app.
Using HashMap seems waste a lot of spaces (more than 23% of heap)

![image](https://user-images.githubusercontent.com/8781032/108928674-2c4d2000-7608-11eb-89a4-3216276d4ad2.png)

![image](https://user-images.githubusercontent.com/8781032/108928684-31aa6a80-7608-11eb-953f-188a9d13932a.png)

**Comment by laksono** [comment]
Merging 2 huge DCA++ databases cause Java "Out of Memory" exception. 

```
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.OutOfMemoryError: Java heap space)
...
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.newNode(HashMap.java:1888)
	at java.base/java.util.HashMap.putVal(HashMap.java:631)
	at java.base/java.util.HashMap.put(HashMap.java:612)
	at edu.rice.cs.hpc.data.db.MetricValueCollectionWithStorage.lambda$0(MetricValueCollectionWithStorage.java:132)
	at edu.rice.cs.hpc.data.db.MetricValueCollectionWithStorage$$Lambda$214/0x00000001004e4208.accept(Unknown Source)
	at java.base/java.util.HashMap.forEach(HashMap.java:1425)
	at edu.rice.cs.hpc.data.db.MetricValueCollectionWithStorage.appendMetrics(MetricValueCollectionWithStorage.java:131)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.copyMetrics(Scope.java:743)
	at edu.rice.cs.hpc.data.experiment.scope.visitors.BaseDuplicateScopeTreesVisitor.accumulateMetrics(BaseDuplicateScopeTreesVisitor.java:104)
	at edu.rice.cs.hpc.data.experiment.scope.visitors.BaseDuplicateScopeTreesVisitor.addMetricColumns(BaseDuplicateScopeTreesVisitor.java:92)
	at edu.rice.cs.hpc.data.experiment.scope.visitors.BaseDuplicateScopeTreesVisitor.mergeInsert(BaseDuplicateScopeTreesVisitor.java:56)
	at edu.rice.cs.hpc.data.experiment.scope.visitors.BaseDuplicateScopeTreesVisitor.visit(BaseDuplicateScopeTreesVisitor.java:44)
	at edu.rice.cs.hpc.data.experiment.scope.LineScope.accept(LineScope.java:135)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:753)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
	at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:758)
```
![image](https://user-images.githubusercontent.com/8781032/115639416-23ac5980-a2da-11eb-83f2-c90014f84d63.png)

**Comment by laksono** [comment]
Opening 2 NWChem databases and doing a filter will cause out of memory exception.
The way we store variables can be critical. 
- The XML parser (or tree builder) has 27% of the total memory consumption.
- Experiment class has almost 20% of the total memory
- Callsite scopes has a combined 25% of the total memory

![image](https://user-images.githubusercontent.com/8781032/116757673-23941400-a9d4-11eb-9dc1-3307fc5fd6f4.png)

![image](https://user-images.githubusercontent.com/8781032/116757419-a5377200-a9d3-11eb-9e87-194c2a861f0e.png)

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpcviewer/-/issues/68)
